using System;
using System.Collections.Generic;

namespace ngenstrings
{
	public class LocalizedString
	{
		private string _key;
		private string _value;
		private string _table;
		private string _comment;

		/// <summary>
		/// Key is the only REQUIRED parameter.
		/// </summary>
		public string Key
		{
			get { return _key; }
			set { _key = value; }
		}
		/// <summary>
		/// (optional) default value may be specified.
		/// If it is not specified, the Key text is used as the default value
		/// </summary>
		public string @Value
		{
			get
			{
				if (String.IsNullOrEmpty(_value)) 
					return _key;
				else
					return _value;
			}
			set { _value = value; }
		}
		/// <summary>
		/// (optional) comment to the translator can be specified in some method overloads
		/// If it is not specified, the method/s where the text appears is used
		/// </summary>
		public string Comment
		{
			get
			{
				if (String.IsNullOrEmpty(_comment)) 
					return InMethodString;
				else
					return _comment;
			}
			set { _comment = value; }
		}
		/// <summary>
		/// (optional) the .strings filename where the translation will be stored.
		/// If empty, the translation will be in the default Localizable.strings file.
		/// </summary>
		public string Table
		{
			get
			{
				if (String.IsNullOrEmpty(_table))
					return "";
				else 
					return _table.Trim(); // return "" if nothing specified, to get default behavior
			}
			set { _table = value; }
		}
		[Obsolete("Not supported")]
		public string Bundle {get;set;} // not used

		public List<string> InMethods = new List<string>();
		public string InMethodString 
		{
			get
			{
				var s = "";
				foreach (string item in InMethods)
				{
					s += item + ", ";
				}
				return s.Trim(',',' ');
			}
		}
		public LocalizedString ()
		{
		}

		public bool IsEmpty 
		{
			get {return String.IsNullOrEmpty(_key) && String.IsNullOrEmpty(_value); }
		}

		public override string ToString ()
		{
			return string.Format("/* {2} */\n\"{0}\" = \"{1}\";\n\n", Key, Value, Comment);
		}
		public string ToVerboseString ()
		{
			return string.Format("/* {3} : {2}\nMethods: {4}*/\n\"{0}\" = \"{1}\";\n\n", Key, Value, Comment, Table, InMethodString);
		}
		public string ToXmlString ()
		{
			return string.Format("<!-- {3} : {2} -->\\n<key>{0}</key>\n>value>{1}</value>\n", Key, Value, Comment, Table);
		}
		public static string FileHeaderString (string assemblyName)
		{
			return String.Format("/* File generated by ngenstrings from assembly {0} on {1} */\n\n"
				, assemblyName
				, DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString() );
		}
		public static string FileHeaderXmlString (string assemblyName)
		{
			return String.Format("<!-- File generated by ngenstrings from assembly {0} on {1} -->\n\n"
				, assemblyName
				, DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString() );
		}
		
	}
}
